### PR TITLE
com.ginkgostreet.negativenegator#3 Fixing PHP 8.0 issues

### PR DESCRIPTION
**Pull request by shaneonabike**
Fixing a few PHP 8.0 issues that are causing this to fail.

### CODE REVIEW

**Comment by shaneonabike** [comment]
@fulltrucker is it possible you could push this patch it's pretty small

**Comment by fulltrucker** [comment]
Hey Shane, looks like I don't have write access to this repo. I assume Michael @ginkgomzd does and could merge it for you. Ginkgo Street Labs has been gone for a number of years at this point, if you're using this extension and would be interested in taking it on let Michael know.

**Comment by shaneonabike** [comment]
Awesome thanks! @ginkgomzd for the time being before I think about possibly moving this to gitlab civicrm is it possible to create a new version just so others can see this has been updated (if it's not too much trouble).

**Comment by caracolmzd** [comment]
No problem. Tagged 1.1

**Pull request merged**
